# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        MainWindow.setStyleSheet("background-color: rgb(27, 42, 73);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.appTitle = QtWidgets.QLabel(self.centralwidget)
        self.appTitle.setGeometry(QtCore.QRect(220, 30, 581, 61))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.appTitle.setFont(font)
        self.appTitle.setStyleSheet("color: rgb(238, 238, 238);")
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 130, 421, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputLabel = QtWidgets.QLabel(self.layoutWidget)
        self.inputLabel.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(18)
        self.inputLabel.setFont(font)
        self.inputLabel.setStyleSheet("color: rgb(238, 238, 238);")
        self.inputLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout.addWidget(self.inputLabel)
        self.inputBox = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        self.inputBox.setFont(font)
        self.inputBox.setStyleSheet("background-color: rgb(237, 247, 250);")
        self.inputBox.setObjectName("inputBox")
        self.verticalLayout.addWidget(self.inputBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(530, 130, 401, 411))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.graphLabel.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(18)
        self.graphLabel.setFont(font)
        self.graphLabel.setStyleSheet("color: rgb(238, 238, 238);")
        self.graphLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.graphLabel.setObjectName("graphLabel")
        self.verticalLayout_2.addWidget(self.graphLabel)
        self.graph = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(40)
        self.graph.setFont(font)
        self.graph.setStyleSheet("background-color: rgb(0, 64, 133);\n"
"color: rgba(238, 238, 238,.4);")
        self.graph.setAlignment(QtCore.Qt.AlignCenter)
        self.graph.setObjectName("graph")
        self.verticalLayout_2.addWidget(self.graph)
        self.languagesList = QtWidgets.QListWidget(self.centralwidget)
        self.languagesList.setGeometry(QtCore.QRect(540, 610, 381, 121))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.languagesList.setFont(font)
        self.languagesList.setStyleSheet("color: rgb(238, 238, 238);\n"
"background-color: rgb(21, 34, 61);")
        self.languagesList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.languagesList.setAlternatingRowColors(False)
        self.languagesList.setObjectName("languagesList")
        self.languagesLabel = QtWidgets.QLabel(self.centralwidget)
        self.languagesLabel.setGeometry(QtCore.QRect(540, 569, 251, 31))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(18)
        self.languagesLabel.setFont(font)
        self.languagesLabel.setStyleSheet("color: rgb(238, 238, 238);")
        self.languagesLabel.setObjectName("languagesLabel")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(90, 620, 381, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.importButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(14)
        self.importButton.setFont(font)
        self.importButton.setStyleSheet("color: rgb(238, 238, 238);")
        self.importButton.setObjectName("importButton")
        self.gridLayout.addWidget(self.importButton, 0, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(14)
        self.runButton.setFont(font)
        self.runButton.setStyleSheet("color: rgb(238, 238, 238);")
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appTitle.setText(_translate("MainWindow", "Language Detector"))
        self.inputLabel.setText(_translate("MainWindow", "Text Input"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Enter Text..."))
        self.graphLabel.setText(_translate("MainWindow", "Prediction Graph"))
        self.graph.setText(_translate("MainWindow", "?"))
        self.languagesList.setSortingEnabled(False)
        self.languagesLabel.setText(_translate("MainWindow", "Detected Language: "))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.runButton.setText(_translate("MainWindow", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
